name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  windows:
    name: Windows (lint + test + build)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Generate build info
        run: dart run scripts/generate_build_info.dart

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Analyze the code for linting errors
        run: flutter analyze lib test

      - name: Run widget tests
        run: flutter test

      - name: Core package - Run tests
        run: dart test packages/core/test

      - name: Build Windows app
        run: flutter build windows --debug

  android:
    name: Android (test + build)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Generate build info
        run: dart run scripts/generate_build_info.dart

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Analyze the code for linting errors
        run: flutter analyze lib test

      - name: Build apk
        run: flutter build apk --debug
